### ISSUE TITLE
version grew-match vs version git

### ISSUE THREAD

**Issue by mmahamdi** [surfacesyntacticud/SUD_French-Spoken#2]
Bonjour, 

En regardant la page de validation SUD pour Paris Stories 2019, je me suis rendue compte que la version d'expérience Fac sur grew-match était différente de celle présente dans ce répertoire. Dans la version disponible ici, certaines phrases n'apparaissent pas dans le bon ordre, certaines ont été découpées en 2, et les relations ont été modifiées. 
Par ex sur grew-match on a : 
ParisStories_2019_experienceFac_39
 peut-être que je pouvais pas , ou alors j'avais peut-être la flemme .
Avec une erreur signalée par rapport à la racine. 
Dans le fichier git on a : 

sent_id = ParisStories_2019_experienceFac_39
 text = peut-être que je pouvais pas ,

Avec beaucoup plus loin : 
sent_id = ParisStories_2019_experienceFac_80
text = ou alors j'avais peut-être la flemme .

Est-ce que je rassemble les 2 arbres, ou alors , du moins, est-ce que je remets la deuxième partie à sa place en lui donnant un nouveau sent_id bis ?

**Comment by bguil** [comment]
Je ne suis pas sûr de comprendre le problème.

Dans https://github.com/surfacesyntacticud/SUD_French-Spoken/commit/30c10dc87b2ad3753e93e710cdd34e8d52e8d6cc, les phrases ont été découpées et les nouveaux morceaux placés à la fin du fichier. Je pense que c'est là que l'ordre  initial des phrases à été perdu.

**Comment by mmahamdi** [comment]
Je me disais que, dans l'exemple que je vous ai donné, c'était une seule unité syntaxique et donc qu'il fallait les rassembler. Dans Rhapsodie, il n'y a pas de coupure entre syntagmes, et comme on est chargées d'uniformiser l'annotation, c'est pour ça que je me posais la question. 

> Dans 30c10dc, les phrases ont été découpées et les nouveaux morceaux placés à la fin du fichier. Je pense que c'est là que l'ordre initial des phrases à été perdu.

D'accord, du coup,  dois-je remettre les phrases dans l'ordre ?

**Comment by bguil** [comment]
Je laisse @sylvainkahane et @kimgerdes répondre sur ce qu'il faut faire. Mais j'ai peur que ce soit beaucoup de boulot pour tout remettre en place.

**Comment by sylvainkahane** [comment]
Deux questions :
1) oui c'est normal d'avoir découpé en deux unités illocutoires, car il y a deux verbes principaux
2) ça aurait du être dans l'ordre. Je ne sais pas pourquoi ça ne l'est pas et ça risque effectivement d'être long à réordonner. Mais peut-être pas : à mon avis c'est une phrase que j'ai coupé en deux dans un 2e traitement et du coup le morceaux découpé a été mis à la fin. Si c'est le cas les problème d'ordre concerne uniquement les UI en fin d'échantillon et ça serait bien de les replacer avec un sent_id=ParisStories_2019_experienceFac_39bis

**Comment by mmahamdi** [comment]
D'accord ce sera fait, merci
